#!/usr/bin/env python3
"""Generate paper/numbers.tex (headline numbers + metrics table) from the
campaign results, so the manuscript always reflects the actual data."""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "results"
OUT = ROOT / "paper" / "numbers.tex"


def times(x: float) -> str:
    return f"${x:.1f}\\times$"


def main():
    m = json.loads((RES / "metrics_passes.json").read_text())
    model = np.load(RES / "model.npz")
    rows = json.loads((RES / "robust.json").read_text())

    red = {k: m["open"]["rms_ac_wc"] / m[k]["rms_ac_wc"]
           for k in ("cpd", "vpd", "pshlqg")}
    drift = np.max(np.abs(model["freqs_end"] / model["freqs"] - 1.0)) * 100
    mc_red = sorted(r["open"] / r["pshlqg"] for r in rows)
    removal_ratio = abs(m["pshlqg_removal"]["rms_ac_wc"]
                        / m["pshlqg"]["rms_ac_wc"] - 1.0) * 100
    surf = (m["open"].get("surf_std", np.nan)
            / m["pshlqg"].get("surf_std", np.nan))

    lines = [
        r"% auto-generated by scripts/fill_numbers.py -- do not edit",
        rf"\newcommand{{\RedPSH}}{{{times(red['pshlqg'])}}}",
        rf"\newcommand{{\RedCPD}}{{{times(red['cpd'])}}}",
        rf"\newcommand{{\RedVPD}}{{{times(red['vpd'])}}}",
        rf"\newcommand{{\UnifOpen}}{{{m['open']['uniformity']:.2f}}}",
        rf"\newcommand{{\UnifPSH}}{{{m['pshlqg']['uniformity']:.2f}}}",
        rf"\newcommand{{\VrmsPSH}}{{\SI{{{m['pshlqg']['v_rms']:.0f}}}{{V}}}}",
        rf"\newcommand{{\SurfPSH}}{{{times(surf)}}}",
        rf"\newcommand{{\MCmedPSH}}{{{times(np.median(mc_red))}}}",
        rf"\newcommand{{\MCminPSH}}{{{times(mc_red[0])}}}",
        rf"\newcommand{{\RemovalDrift}}{{{drift:.2f}\%}}",
        rf"\newcommand{{\RemovalPerf}}{{{removal_ratio:.0f}\%}}",
    ]

    tab = [r"\begin{tabular}{lccccc}", r"\toprule",
           r"Controller & AC RMS [$\mu$m] & max $|\wc|$ [$\mu$m] & "
           r"uniformity & $V_{\mathrm{RMS}}$ [V] & surf.\ std [$\mu$m]\\",
           r"\midrule"]
    lab = {"open": "No control", "cpd": "CPD", "vpd": "VPD",
           "pshlqg": "PSH-LQG"}
    for k in ("open", "cpd", "vpd", "pshlqg"):
        s = m[k]
        tab.append(
            f"{lab[k]} & {s['rms_ac_wc']*1e6:.2f} & {s['max_wc']*1e6:.1f} & "
            f"{s['uniformity']:.2f} & {s['v_rms']:.0f} & "
            f"{s.get('surf_std', float('nan'))*1e6:.2f}\\\\")
    tab += [r"\bottomrule", r"\end{tabular}"]
    lines.append(r"\newcommand{\InsertMetricsTable}{%")
    lines += [t + "%" for t in tab]
    lines.append("}")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")
    print("\n".join(lines[:12]))


if __name__ == "__main__":
    main()
